/**
 * @arch archcodex.core.types
 * @intent:stateless
 *
 * Type definitions for the spec inferrer.
 * Split from inferrer.ts for file size compliance.
 */

/**
 * Options for spec inference.
 */
export interface InferOptions {
  projectRoot?: string;
  /** Override auto-detected base spec */
  inherits?: string;
}

/**
 * Result of spec inference.
 */
export interface InferResult {
  valid: boolean;
  specId: string;
  yaml: string;
  detectedPatterns: DetectedPattern;
  errors: Array<{ code: string; message: string }>;
}

/**
 * Patterns detected from implementation code.
 */
export interface DetectedPattern {
  baseSpec: string;
  security: { authentication: 'required' | 'optional' | 'none' };
  effects: Array<{ type: string; detail?: string }>;
  errorCodes: string[];
  archTag?: string;
}

/**
 * Mapping from TypeScript type string to spec type.
 */
export interface TypeMapping {
  specType: 'string' | 'number' | 'boolean' | 'object' | 'array' | 'id' | 'enum' | 'void';
  table?: string;
  values?: string[];
  properties?: Record<string, TypeMapping>;
  items?: TypeMapping;
  description?: string;
}

/**
 * Options for updating an existing spec.
 */
export interface InferUpdateOptions {
  projectRoot?: string;
}

/**
 * Result of spec update/merge.
 */
export interface InferUpdateResult {
  valid: boolean;
  yaml: string;
  mergeReport: MergeReport;
  errors: Array<{ code: string; message: string }>;
}

/**
 * Report of what changed during merge.
 */
export interface MergeReport {
  addedInputs: string[];
  removedInputs: string[];
  addedOutputs: string[];
  removedOutputs: string[];
  preservedSections: string[];
}

/**
 * Code context gathered for LLM enrichment.
 */
export interface CodeContext {
  /** Type definitions imported by the function */
  importedTypes: Array<{ name: string; definition: string; filePath: string }>;
  /** Names of functions called from the implementation */
  calledFunctions: string[];
  /** Files read for context with relevance notes */
  contextFiles: Array<{ path: string; relevance: string }>;
}

/**
 * Request for LLM enrichment of a spec skeleton.
 */
export interface EnrichmentRequest {
  filePath: string;
  content: string;
  exportName: string;
  skeleton: InferResult;
  context: CodeContext;
}

/**
 * Enriched sections generated by LLM.
 */
export interface EnrichedSections {
  goal: string;
  intent: string;
  successExamples: Array<{
    name: string;
    given: Record<string, unknown>;
    then: Record<string, unknown>;
  }>;
  errorExamples: Array<{
    name: string;
    given: Record<string, unknown>;
    then: Record<string, unknown>;
  }>;
  invariants: string[];
}
