---

archcodex.infra.git:
  inherits: archcodex.infra.adapter
  description: Git integration - staged files, commit info, repository state
  rationale: |
    Git operations adapter for version control integration.
    Wraps simple-git or child_process for git commands.

    Use for: Files that query git state (staged files, branch info, commits).
    Don't use for: General file I/O (use infra.fs), config loading (use infra.config).
  # All constraints inherited from infra.adapter (forbid_import: chalk, ts-morph, ../core, commander, ../cli)
  hints:
    - Handle git not installed gracefully (return empty/defaults)
    - Return empty arrays for missing repo state
    - Cache expensive git operations where appropriate
    - Use child_process or simple-git for git commands
