---

archcodex.infra.validator-support:
  inherits: archcodex.infra
  mixins:
    - ocp
  description: Validator subsystem support - registry, capabilities, types, and AST utilities
  rationale: |
    Support infrastructure for the language validator plugin system.
    Defines the contracts (interfaces, types, capabilities), the registry
    that manages validator instances, and shared AST extraction utilities.

    Includes tree-sitter based AST extraction for Python and Go languages,
    providing common traversal, extraction, and context management functions.

    Use for: Validator registry, language capabilities, validator interfaces/types,
             tree-sitter AST extraction utilities.
    Don't use for: Actual language validator implementations (use infra.validator).
  reference_implementations:
    - src/validators/validator-registry.ts
    - src/validators/capabilities.ts
    - src/validators/register.ts
    - src/validators/tree-sitter/TreeSitterUtils.ts
    - src/validators/tree-sitter/python-ast.ts
    - src/validators/tree-sitter/go-ast.ts
  file_pattern: ${name}.ts
  default_path: src/validators
  constraints:
    - rule: forbid_import
      value:
        - commander
        - chalk
        - ../cli
      severity: error
      why: "[DIP] Validator support must not depend on CLI concerns"
  hints:
    - "[OCP] Support new languages by extending capabilities and registering new validators"
    - "[DIP] Define interfaces here, implementations go in infra.validator"
    - "Tree-sitter AST extraction provides language-agnostic traversal patterns"

archcodex.infra.validator:
  inherits: archcodex.infra
  mixins:
    - ocp
    - lsp
  description: Language-specific source code validators
  rationale: |
    Validators that analyze source code structure and produce SemanticModel.
    Each validator implements ILanguageValidator interface and uses a parser
    appropriate for its target language:
    - TypeScript/JavaScript: ts-morph (TypeScript compiler API)
    - Python: tree-sitter-python (AST parsing)
    - Go: tree-sitter-go (AST parsing)

    Use for: Files that parse and analyze source code for constraint validation.
    Don't use for: Constraint logic itself (use core.domain.constraint).
  reference_implementations:
    - src/validators/typescript.ts
    - src/validators/python.ts
    - src/validators/go.ts
  file_pattern: ${name}.ts
  default_path: src/validators
  code_pattern: |-
    import type { ILanguageValidator } from './interface.types.js';
    import type { SemanticModel, LanguageCapabilities } from './semantic.types.js';

    export class XxxValidator implements ILanguageValidator {
      readonly supportedLanguages = ['xxx'];
      readonly supportedExtensions = ['.xxx'];
      readonly capabilities: LanguageCapabilities = { ... };

      async parseFile(filePath: string, content?: string): Promise<SemanticModel> {
        // Parse file into SemanticModel using language-appropriate parser
      }

      dispose(): void {
        // Clean up resources if needed
      }
    }
  constraints:
    - rule: require_import
      value:
        - ./interface.types.js
      severity: error
      why: "[LSP] All validators must implement ILanguageValidator"
    - rule: require_import
      value:
        - ./semantic.types.js
      severity: error
      why: All validators must produce SemanticModel
    - rule: forbid_import
      value:
        - commander
        - chalk
      severity: error
      why: "[DIP] Validators must not depend on CLI concerns"
      alternative: src/utils/logger
  hints:
    - text: "[LSP] Implement ILanguageValidator interface"
      example: code://src/validators/typescript.ts
    - "[OCP] Add new language support via new validator classes"
    - Parse once, query multiple times
